# Generated by Django 6.1.1 on 2026-09-15 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0001_initial'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, help_text="Couleur d'affichage, ex: #3498db", max_length=20)),
                ('concentration', models.CharField(blank=True, help_text='Ex: 0.1 mol/L', max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='reagents/')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='experiments.experiment')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.reagent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
