# Generated by Django 6.1.1 on 2026-09-16 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0001_initial'),
        ('laboratory', '0002_reagent_experimentreagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedReagentAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_volume', models.FloatField(help_text='Volume correct attendu, en mL')),
                ('tolerance', models.FloatField(default=1.0, help_text="Marge d'erreur acceptée, en mL")),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_reagents', to='experiments.experiment')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.reagent')),
            ],
            options={
                'unique_together': {('experiment', 'reagent')},
            },
        ),
    ]
