# Generated by Django 6.1.1 on 2026-09-17 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_expectedreagentamount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBenchReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pubchem_cid', models.PositiveIntegerField(blank=True, null=True)),
                ('molecular_formula', models.CharField(blank=True, max_length=100)),
                ('molecular_weight', models.FloatField(blank=True, help_text='Masse molaire en g/mol', null=True)),
                ('canonical_smiles', models.TextField(blank=True)),
                ('isomeric_smiles', models.TextField(blank=True)),
                ('inchi', models.TextField(blank=True)),
                ('inchikey', models.CharField(blank=True, max_length=30)),
                ('synonyms', models.TextField(blank=True, help_text='Synonymes séparés par des virgules')),
                ('image_url', models.URLField(blank=True)),
                ('color', models.CharField(blank=True, default='#3498db', max_length=20)),
                ('volume_ml', models.FloatField(default=0.0, help_text="Volume choisi par l'utilisateur, en mL")),
                ('concentration', models.FloatField(blank=True, help_text='Concentration en mol/L (optionnelle)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bench_reagents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'pubchem_cid')},
            },
        ),
    ]
