# Generated by Django 6.1.1 on 2026-09-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_userbenchreagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='ph',
            field=models.FloatField(blank=True, help_text='pH de la solution telle que stockée (optionnel, pour le laboratoire libre)', null=True),
        ),
    ]
