# Generated by Django 6.1.1 on 2026-09-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_reagent_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='hazards',
            field=models.CharField(blank=True, default='', help_text='Pictogrammes SGH séparés par des virgules, ex : GHS05,GHS07', max_length=120),
        ),
        migrations.AddField(
            model_name='reagent',
            name='incompatible_with',
            field=models.ManyToManyField(blank=True, help_text='Réactifs à ne pas mélanger avec celui-ci (alerte de sécurité).', to='laboratory.reagent'),
        ),
        migrations.AddField(
            model_name='reagent',
            name='safety_advice',
            field=models.TextField(blank=True, default='', help_text='Conseils de manipulation affichés avant versement.'),
        ),
        migrations.AddField(
            model_name='userbenchreagent',
            name='hazard_statements',
            field=models.TextField(blank=True, default='', help_text='Mentions de danger PubChem (ex : H314: ...), séparées par « ; ».'),
        ),
        migrations.AddField(
            model_name='userbenchreagent',
            name='hazards',
            field=models.CharField(blank=True, default='', help_text='Pictogrammes SGH séparés par des virgules, ex : GHS05,GHS07', max_length=120),
        ),
    ]
