# Generated by Django 6.1.1 on 2026-09-18 07:26

from django.db import migrations


def backfill_leaders(apps, schema_editor):
    Group = apps.get_model("groups", "Group")
    for group in Group.objects.filter(leader__isnull=True):
        group.leader = group.created_by
        group.save(update_fields=["leader"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_leader'),
    ]

    operations = [
        migrations.RunPython(backfill_leaders, noop),
    ]
