"""
Django settings for ChemLab project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import os
import sys

import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    'django-insecure-^7mld%+(a+a+&_*us3wklr#la=ld2h$7n4@ggf#p$07g1azg8l'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]

# Origines de confiance pour les POST (obligatoire en prod HTTPS,
# sinon tous les formulaires sont rejetés en 403 CSRF).
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',

    'accounts',
    'experiments',
    'laboratory',
    'groups',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Sécurité : exige une authentification sur toute la plateforme,
    # sauf pour les pages publiques (accueil, catalogue, connexion...).
    'accounts.middleware.RequireLoginMiddleware',
]

ROOT_URLCONF = 'ChemLab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "groups.context_processors.pending_invitations_count",
                "ChemLab.admin_dashboard.dashboard_stats",
            ],
        },
    },
]

WSGI_APPLICATION = 'ChemLab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases


DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', 'sqlite:///db.sqlite3')
    )
}

if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'test_db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Dossier de collecte des statiques en production (collectstatic, WhiteNoise).
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "laboratory:dashboard"
LOGOUT_REDIRECT_URL = "laboratory:home"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get(
    "DJANGO_DEFAULT_FROM_EMAIL", "ChemLab Virtual <noreply@chemlab.local>"
)


# Backend d'authentification : django-axes verrouille les comptes
# après échecs répétés (nécessite la requête dans authenticate()).
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# ---------------------------------------------------------------------------
# Anti brute-force (django-axes) : verrouillage après échecs répétés
# ---------------------------------------------------------------------------

# Verrouillage au 5e échec, déblocage auto après 1 heure.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1

# Verrouille le couple (compte, IP) : un attaquant ne bloque pas les
# autres utilisateurs, et un utilisateur légitime ailleurs n'est pas impacté.
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]

# Derrière le proxy de l'hébergeur (ex. Render), l'IP client se lit dans
# X-Forwarded-For avec un seul proxy de confiance.
AXES_IPWARE_PROXY_COUNT = 1


# ---------------------------------------------------------------------------
# Sécurité de la plateforme (normes Django / OWASP)
# ---------------------------------------------------------------------------


def _env_true(key, default="false"):
    """Lit une variable d'environnement booléenne."""
    return os.environ.get(key, default).lower() in ("1", "true", "yes")


# --- En-têtes de sécurité (safe en local HTTP) ---
# Empêche le navigateur de deviner le type de contenu des réponses.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Interdit l'affichage de la plateforme dans un <iframe> (anti-clickjacking).
X_FRAME_OPTIONS = "DENY"

# Politique de référrent : on limite les informations transmises à un site tiers.
SECURE_REFERRER_POLICY = "same-origin"

# Isole le contexte de navigation de l'application vis-à-vis des autres onglets.
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

# --- HTTPS (activé en production via les variables d'environnement) ---
_SECURE = _env_true("DJANGO_SECURE_SSL_REDIRECT")
if _SECURE:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # HSTS : force le navigateur à n'utiliser que HTTPS pendant 1 an.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# --- Cookies de session / CSRF ---
# Le cookie de session n'est accessible que via HTTP (jamais en JavaScript).
SESSION_COOKIE_HTTPONLY = True

# Envoi restreint des cookies (protection CSRF par SameSite).
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Cookie de session chiffré uniquement en HTTPS.
if _env_true("DJANGO_SESSION_COOKIE_SECURE"):
    SESSION_COOKIE_SECURE = True

# Cookie de CSRF chiffré uniquement en HTTPS.
if _env_true("DJANGO_CSRF_COOKIE_SECURE"):
    CSRF_COOKIE_SECURE = True

# Le jeton CSRF est stocké dans la session (et jamais dans un cookie persistant).
CSRF_USE_SESSIONS = True

